### ISSUE TITLE
66.加一个另外的写法

### ISSUE THREAD

**Issue by zdylzdyl** [cy69855522/Shortest-LeetCode-Python-Solutions#1]
66题，写了一个另外的简单写法，没有用map函数
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        return [int(i) for i in str(int(str(digits)[1:-1].replace(',', '').replace(' ', '')) + 1)]

**Comment by cy69855522** [comment]
感谢分享！直接对list执行str确实是feasible，但鉴于项目主题，此处仅收录 1.在代码量上明显优于现有解的最短代码  2.思路更高效的一般解法（作为补充放在首选解之后）🤝
