### ISSUE TITLE
二维数组 对角线遍历 解析有点问题

### ISSUE THREAD

**Issue by dagongji10** [cy69855522/Shortest-LeetCode-Python-Solutions#19]
`如果 对角线元素个数 是偶数则应该把 temp 反转` 有误，比如 3*8 的矩阵，后面的对角线元素个数都是3，那就一直不会翻转，这是不对的。
代码里面是根据 `l` 的奇偶性来判断是否反转，是正确的。

**Comment by cy69855522** [comment]
是的，注释写错了，应该是对角线索引，3Q~
