### ISSUE TITLE
414.两行Python写法

### ISSUE THREAD

**Issue by zdylzdyl** [cy69855522/Shortest-LeetCode-Python-Solutions#2]
`class Solution:
    def thirdMax(self, nums):
        nums = sorted(list(set(nums)))
        return (len(nums) < 3) * nums[-1] or nums[-3]
`

**Comment by cy69855522** [comment]
感谢分享，但题目有明确要求时间复杂度在O(N)之内，python的sorted函数使用的是timesort，时间复杂度为O(NlogN)不符合题意。另外一个小tip，在github写代码的时候可以把代码放进两行```里面，可以保持代码结构，或者直接点击网页编辑框的<>符号。
