### ISSUE TITLE
addTwoNumbers－shortest solution

### ISSUE THREAD

**Issue by PiseyYou** [cy69855522/Shortest-LeetCode-Python-Solutions#4]
def addTwoNumbers(l1, l2):

    temp1 = int(''.join(map(str,l1[::-1])))

    temp2 = int(''.join(map(str,l2[::-1])))

    return (map(int,list(str(temp1+temp2)[::-1])))

**Comment by PiseyYou** [comment]
def addTwoNumbers(l1, l2):

    temp1 = int(''.join(map(str,l1[::-1])))
    temp2 = int(''.join(map(str,l2[::-1])))
    return (map(int,list(str(temp1+temp2)[::-1])))

**Comment by cy69855522** [comment]
```python
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def addTwoNumbers(self, l1: ListNode, l2: ListNode) -> ListNode:
        temp1 = int(''.join(map(str,l1[::-1])))
        temp2 = int(''.join(map(str,l2[::-1])))
        return (map(int,list(str(temp1+temp2)[::-1])))
```
```python
Runtime Error Message:
Line 9: TypeError: 'ListNode' object is not subscriptable
Last executed input:
[2,4,3]
[5,6,4]
```
Thanks for your suggestion, but there seems to be something wrong with this code.

**Comment by paulxin001** [comment]
I think you are right, ListNode can not use this method. thanks for your recommendation.------------------ 原始邮件 ------------------
发件人: "Knife丶"<notifications@github.com>
发送时间: 2019年8月27日(星期二) 晚上11:16
收件人: "cy69855522/Shortest-LeetCode-Python-Solutions"<Shortest-LeetCode-Python-Solutions@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [cy69855522/Shortest-LeetCode-Python-Solutions] addTwoNumbers－shortest solution (#4)


# Definition for singly-linked list. # class ListNode: #     def __init__(self, x): #         self.val = x #         self.next = None class Solution:     def addTwoNumbers(self, l1: ListNode, l2: ListNode) -> ListNode:         temp1 = int(''.join(map(str,l1[::-1])))         temp2 = int(''.join(map(str,l2[::-1])))         return (map(int,list(str(temp1+temp2)[::-1])))  Runtime Error Message: Line 9: TypeError: 'ListNode' object is not subscriptable Last executed input: [2,4,3] [5,6,4]
 
Thanks for your suggestion, but there seems to be something wrong with this code.
 
&mdash;
