### ISSUE TITLE
33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by ajinwu** [cy69855522/Shortest-LeetCode-Python-Solutions#5]
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        if target in nums:
            return nums.index(target)
        else:
            return -1

**Comment by cy69855522** [comment]
Thank you for your proposal, your solution is clear and elegant, but there is a requirement in this problem that the time complexity of the algorithm should be controlled within `O(logN)`. The time complexities of `in` and `index` are both `O(N)`, and the time complexity of the overall algorithm is `O(N)`, >`O(logN)`.
